# Uncomment the next line to define a global platform for your project
platform :ios, '10.0'


target 'SwiftiOSApp' do
    # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
    use_frameworks!
#    pod 'Alamofire'
    pod 'SwiftLiteKit', '0.9.2'
    pod 'YYKit'
    pod 'SnapKit'
    pod 'TYPagerController'
#    pod 'Hero'
    pod 'Closures'
    pod 'JRSwizzle'
#    pod 'AudioKit'
#    pod 'SwiftRandom', :git => 'https://github.com/thellimist/SwiftRandom.git'
#    pod 'RealmSwift'
#    pod 'Aspects'
#    pod 'WebViewJavascriptBridge'
    #    pod 'SwiftyBeaver'
    #    pod 'FilesProvider', :path => '/Users/moqiaowen/Documents/学习Git/FilesProvider'
    #    pod 'FilesProvider'
    
end

#post_install do |installer|
#    # 提高 pod 库编译速度
#    installer.pods_project.targets.each do |target|
#        target.build_configurations.each do |config|
#            
#            if config.name == 'Debug'
#                config.build_settings['SWIFT_OPTIMIZATION_LEVEL'] = '-Onone'
#                else
#                config.build_settings['SWIFT_OPTIMIZATION_LEVEL'] = '-Osize'
#            end
#            
#            if config.name == 'Debug'
#                config.build_settings['SWIFT_COMPILATION_MODE'] = 'singlefile'
#                else
#                config.build_settings['SWIFT_COMPILATION_MODE'] = 'wholemodule'
#            end
#        end
#    end
#end


