# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'UIDynamicDemo' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

    pod 'SwiftLiteKit', :path => '/Users/moqiaowen/Documents/个人Git/SwiftLiteKit/'

    pod 'RandomKit'
end
