# Uncomment this line to define a global platform for your project
# platform :ios, '9.0'

target 'LearnReactiveCoca' do
  # Comment this line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for LearnReactiveCoca
#  pod 'ReactiveSwift', :git => 'https://github.com/ReactiveCocoa/ReactiveSwift.git'
#  pod 'ReactiveCocoa', '~> 5.0.0-alpha.3'
   pod 'ReactiveSwift', '1.0.0-alpha.4'
end
