use_frameworks!

target 'RxSwiftPlayground' do
pod 'RxSwift'
pod 'RxCocoa'
#pod 'SwiftLiteKit', :path => '/Users/moqiaowen/Documents/个人Git/SwiftLiteKit/'
pod 'SwiftLiteKit'
end

target 'RxCocoaDemo' do
    pod 'RxSwift'
    pod 'RxCocoa'
    pod 'Alamofire', '~> 4.5.0'
    pod 'SwiftyJSON'
    pod 'AlamofireObjectMapper'
    pod 'AlamofireLogger', '~> 0.2.0'
#    pod 'SwiftLiteKit', :path => '/Users/moqiaowen/Documents/个人Git/SwiftLiteKit/'
pod 'SwiftLiteKit'

end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['CONFIGURATION_BUILD_DIR'] = '$PODS_CONFIGURATION_BUILD_DIR'
      config.build_settings['SWIFT_VERSION'] = '3.2'
    end
  end
end
